'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成�?'     对此文件的更改可能会导致不正确的行为，并且如�?'     重新生成代码，这些更改将会丢失�?' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等�?    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager
        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例�?        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    resourceMan = New Global.System.Resources.ResourceManager("OmniMixFrontend.Resources", GetType(Resources).Assembly)
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  重写当前线程�?CurrentUICulture 属性，对使用此强类型资源类的所有资源查找执行重写�?        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        Friend ReadOnly Property CacheCow_Client() As Byte()
            Get
                Return CType(ResourceManager.GetObject("CacheCow.Client", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property CacheCow_Client_FileStore() As Byte()
            Get
                Return CType(ResourceManager.GetObject("CacheCow.Client.FileStore", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property CacheCow_Common() As Byte()
            Get
                Return CType(ResourceManager.GetObject("CacheCow.Common", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property Imazen_WebP() As Byte()
            Get
                Return CType(ResourceManager.GetObject("Imazen.WebP", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property libwebp64() As Byte()
            Get
                Return CType(ResourceManager.GetObject("libwebp64", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property NAudio() As Byte()
            Get
                Return CType(ResourceManager.GetObject("NAudio", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property Newtonsoft_Json() As Byte()
            Get
                Return CType(ResourceManager.GetObject("Newtonsoft.Json", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property Ookii_Dialogs_Wpf() As Byte()
            Get
                Return CType(ResourceManager.GetObject("Ookii.Dialogs.Wpf", resourceCulture), Byte())
            End Get
        End Property

        Friend ReadOnly Property System_Net_Http_Formatting() As Byte()
            Get
                Return CType(ResourceManager.GetObject("System.Net.Http.Formatting", resourceCulture), Byte())
            End Get
        End Property

    End Module
End Namespace
